### ISSUE TITLE
Recursive minibuffer isearch-edit-string produces Completions buffer

### ISSUE THREAD

**Issue by protesilaos** [oantolin/live-completions#1]
Thank you @oantolin for sharing this package!

If I have the "Completions" open, say, after running `C-h f` and then move to another buffer in order to isearch for something, any attempt at `isearch-edit-string` (`M-e`) will produce another completions buffer (contrary to the standard behaviour where you just edit the minibuffer's text).

Steps I followed on `emacs -Q`:

1. Add contents:

```elisp
(add-to-list 'load-path "/path/to/live-completions/")

(require 'live-completions)

(live-completions-mode 1)
```
 
2. Run `C-h f test`.

3. Do `C-x o`.

4. Then `C-s tes` followed by `M-e`.

Tried with GNU Emacs 27.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.17, cairo version 1.17.3) of 2020-04-20.

**Comment by oantolin** [comment]
Easy to diagnose, but a bit of a headscratcher to fix cleanly and in a general way. I'll think about it some more. 

If it's any consolation, icomplete has the same problem!

**Comment by protesilaos** [comment]
Oh yes, it happens in icomplete too.  I guess I never realised because it does it inside the minibuffer…

**Comment by oantolin** [comment]
OK, I think I got it fixed. I tried several nestings of recursive minibuffers some that want completion and some that don't. It seems to be doing the right thing.

Although icomplete has the same bug, it felt worse here, because the *Completions* buffer feels like it should be sturdier, like it shouldn't get clobbered without good reason.

**Comment by protesilaos** [comment]
I can confirm that it works.  Thanks!

**Comment by oantolin** [comment]
Great! Closing, then.
