### ISSUE TITLE
Do you need colours?

### ISSUE THREAD

**Issue by protesilaos** [oantolin/live-completions#2]
In case you need some tweaks to the greens, the following do that while also specifying a foreground so that it overrides that of the completion's matching characters (in the interest of readability):

```elisp
(defface live-completions-forceable-candidate
  '((default :weight bold)
    (((class color) (min-colors 88) (background dark)) :background "#00422a" :foreground "#9ff0cf")
    (((class color) (min-colors 88) (background light)) :background "#aceaac" :foreground "#004c00")
    (t :foreground "blue"))
  "Face for the candidate that force-completion would select."
  :group 'live-completions)
```

Demo:

![Screenshot from 2020-05-05 19-25-49](https://user-images.githubusercontent.com/12828033/81090484-7a245a80-8f06-11ea-87f5-1d4827ed31fc.png)

![Screenshot from 2020-05-05 19-25-55](https://user-images.githubusercontent.com/12828033/81090493-7bee1e00-8f06-11ea-9b31-013ee77d27a7.png)

**Comment by oantolin** [comment]
I actually like being able to see where the match is, even in the foreceable candidates. I like these shades of green, but maybe would prefer not to have a foreground. What do you think about being able to see where the match is? Is there some accessibility problem with the contrast?

(Aside about `icomplete`: I was even thinking of simply removing the special face for the first match in `icomplete` because (1) I'd like to see how it matches, (2) I don't need it highlighted there to know which one it is: it's always the first one!)

**Comment by protesilaos** [comment]
I see.  Also makes sense for icomplete.

Then you would need to somehow be able to control the colour of the matching characters when these are over the greens.  Otherwise you may have a light cyan on top of a light green or similar combinations that are hard to track (though a bold weight can help a bit).

Maybe overlay those characters with another background?  Or add an underline to them?  I am not sure how such an effect can be achieved.

This would obviously not be an issue if all the minibuffer's completion faces where repurposed for this mode and adapted accordingly (but that would mean overriding the faces of, e.g. `orderless`).

**Comment by oantolin** [comment]
I'd rather not start messing with faces from other parts. I'd say if we can find a background for which the default faces for completions-common-part and all the orderless-match-face-[0-3] are readable, then we keep just the background. If we can't find such a background then we pick a nice background (like the ones you chose above) and override the foreground as you did.

Now, to *me* those background colors you pick look just fine with the completions-common-part and orderless match faces, I don't personally think there are readability problems, so I'd vote for keeping the background colors you chose and removing the foreground attribute. But I'll definitely defer to your judgement on this matter: if you think there's a readability problem, we can keep the foreground (I might remove it in my personal configuration).

**Comment by protesilaos** [comment]
> if we can find a background for which the default faces for completions-common-part and all the orderless-match-face-[0-3] are readable, then we keep just the background

I will prioritise this and report back to you.

> so I'd vote for keeping the background colors you chose and removing the foreground attribute

Well, I do not feel I have a vote here: it is your package and I am willing to follow your lead.

Just my two cents: orderless is in a better position because of the bold weight.  Whereas the `completions-common-part` (used by the built-in styles) are not bold by default.  From `minibuffer.el`:

```elisp
(defface completions-common-part
  '((((class color) (min-colors 16) (background light)) :foreground "blue3")
    (((class color) (min-colors 16) (background dark)) :foreground "lightblue"))
  "Face for the parts of completions which matched the pattern.
See also the face `completions-first-difference'.")
```

**Comment by protesilaos** [comment]
Light theme: I found a "green" colour (`#c4ffe0`) that would work perfectly well contrast-wise with orderless faces and those of standard completions.

This table shows the contrast ratio.  Obviously you could go as low as 4.5:1 and still have a good accessibility rating (WCAG AA), though not the highest.

```
|         | #c4ffe0 | Comment                      |
|---------+---------+------------------------------|
| #005a68 |    7.03 | completions-common-part      |
| #0000bb |    10.9 | completions-first-difference |
|---------+---------+------------------------------|
| #223fbf |    7.39 | orderless-match-face-0       |
| #8f0075 |    7.72 | orderless-match-face-1       |
| #095f1c |    7.02 | orderless-match-face-2       |
| #804000 |    7.06 | orderless-match-face-3       |
```

Also works with the colours for the `emacs -Q` theme.

I will try to find one for the dark colours as well.

EDIT: screenshot using `rainbow-mode`

![Screenshot from 2020-05-05 23-24-44](https://user-images.githubusercontent.com/12828033/81112669-b0be9d00-8f27-11ea-89c7-8258dcaaffbc.png)

EDIT 2: Showing it in action (click to enlarge).

![Screenshot from 2020-05-05 23-28-28](https://user-images.githubusercontent.com/12828033/81113008-32aec600-8f28-11ea-8ff1-45b85fa27bb0.png)

**Comment by oantolin** [comment]
Perfect! Thank you! The screenshot in action looks fantastic.

This is why I defer to your opinion for these things. I want the defaults to be accessible but I don't even know how to compute contrast ratios, let alone what the reasonable range for those numbers is.

I'd very grateful if you managed to pull this off for the dark modes too.

**Comment by protesilaos** [comment]
I will do it for the dark as well.  Though it will require a very dark, pine-like sort of green. We'll see.

Anyway, this is the formula https://www.w3.org/TR/WCAG20-TECHS/G18.html.  And this is the poorly-designed shell script i wrote about a year ago when I was practicing bash parameter expansion: https://gitlab.com/protesilaos/dotfiles/-/blob/master/bin/bin/clr

(my intention is to implement this in elisp, mostly as a learning exercise, and to also figure out how to do formulas with org tables)

**Comment by protesilaos** [comment]
Same principle for the dark colours.  A green colour is not doable.  It would have to go as low as `#002000`, which is too dark for this case.  Instead I have two options, dark blue `#10104f` and dark purple `#240a45`.  The table:

```
|         | #10104f | #240a45 | comment                      |
|---------+---------+---------+------------------------------|
| #6ae4b9 |   11.00 |   11.10 | completions-common-part      |
| #00baf4 |    7.71 |    7.74 | completions-first-difference |
|---------+---------+---------+------------------------------|
| #72a4ff |    7.00 |    7.03 | orderless-match-face-0       |
| #f78fe7 |    8.30 |    8.33 | orderless-match-face-1       |
| #58dd13 |    9.73 |    9.77 | orderless-match-face-2       |
| #e5f040 |   13.90 |   14.00 | orderless-match-face-3       |
```

The `rainbow-mode`:

![Screenshot from 2020-05-05 23-59-06](https://user-images.githubusercontent.com/12828033/81115462-6db2f880-8f2c-11ea-9cfa-998527001e95.png)

And in action:

![Screenshot from 2020-05-05 23-50-38](https://user-images.githubusercontent.com/12828033/81115532-83c0b900-8f2c-11ea-8b7c-ae03ed1a9e56.png)

![Screenshot from 2020-05-05 23-56-20](https://user-images.githubusercontent.com/12828033/81115500-7a375100-8f2c-11ea-82bf-bbcc50026599.png)

**Comment by oantolin** [comment]
Thanks! They both look good. I feel like the match highlighting stands out equally well against them, but the blue stands out slightly more then the purple against the background. I'll use the dark blue.

**Comment by oantolin** [comment]
I know you said you wanted to do this yourself, but since I wanted to play around with the formulas, I wrote them in Emacs Lisp:

```elisp
(defun rel-lum (hex)
  (apply #'+
         (cl-mapcar
          (lambda (k x)
            (* k (if (<= x 0.03928)
                     (/ x 12.92)
                   (expt (/ (+ x 0.055) 1.055) 2.4))))
          '(0.2126 0.7152 0.0722)
          (color-name-to-rgb hex))))

(defun contrast (c1 c2)
  (let ((ct (/ (+ (rel-lum c1) 0.05)
               (+ (rel-lum c2) 0.05))))
    (max ct (/ ct))))
```

And here's what an org mode table using them looks like:

```
|         | #10104f | #240a45 | comment                      |
|---------+---------+---------+------------------------------|
| #6ae4b9 |   11.09 |   11.14 | completions-common-part      |
| #00baf4 |    7.72 |    7.75 | completions-first-difference |
|---------+---------+---------+------------------------------|
| #72a4ff |    7.01 |    7.03 | orderless-match-face-0       |
| #f78fe7 |    8.30 |    8.33 | orderless-match-face-1       |
| #58dd13 |    9.73 |    9.77 | orderless-match-face-2       |
| #e5f040 |   13.95 |   14.01 | orderless-match-face-3       |
#+TBLFM: $2='(contrast $1 @1$2);%0.2f::$3='(contrast $1 @1$3);%0.2f
```

**Comment by protesilaos** [comment]
Oh this is very nice and much more straightforward.  Thanks!
