### ISSUE TITLE
ffap doesn't work from a live completions buffer

### ISSUE THREAD

**Issue by oantolin** [oantolin/live-completions#4]
When you are completing file names without live-completions-mode, you can use `ffap` (or `C-x C-f M-n`) on a completion in the `*Completions*` buffer to open it. But for some reason this doesn't work when live-completions-mode is on.

**Comment by oantolin** [comment]
Weird, `M-x ffap` doesn't work, but calling `ffap` from a keybinding does.

**Comment by protesilaos** [comment]
This is specific to file names?  Would `ffap-file-at-point` be worth exploring?

**Comment by oantolin** [comment]
I'm closing this issue since I suspect it is complicated and I don't care about it anymore (thanks to [embark](https://github.com/oantolin/embark)). If anybody else cares about this, please reopen.
