### ISSUE TITLE
find-file fails when setting sort-order to 'cycle

### ISSUE THREAD

**Issue by fgeller** [oantolin/live-completions#5]
Hi and thank you for your Emacs packages! 

I'm running into a small issue with `find-file` when I use the following setup:

```emacs-lisp
(require 'live-completions)
(live-completions-mode +1)
(setq live-completions-sort-order 'cycle)
(call-interactively 'find-file)
```
Evaluationg each form throws up a backtrace, or when run via `M-x find-file` this message is printed:
```
Error running timer ‘live-completions--update’: (wrong-type-argument number-or-marker-p nil)
```
I've tested this with
```
emacs -Q -l live-completions.el test.el
```
where `test.el` is the above snippet, and evaluated each form in turn. If relevant, `emacs-version` prints `GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.4.0) of 2020-04-29`

Not an urgent issue in my eyes, for now I'm not customizing `live-completions-sort-order`. 

Thanks for your time!

**Comment by oantolin** [comment]
I completely rewrote the cycle order case. It seems to be working now, please test.

**Comment by fgeller** [comment]
works! thanks @oantolin !
